homeassistant:
  name: Home Farm Close
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 10
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

frontend:
  themes: !include themes.yaml
  extra_html_url:
    - /local/custom_ui/state-card-floorplan.html
    - /local/custom_ui/state-card-custom-ui.html

config:
http:
  api_password: !secret http_password
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: True
  login_attempts_threshold: 3
mqtt:
  broker: localhost
notify:
  - name: slack
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#home'
recorder:
  purge_interval: 1
  purge_keep_days: 7
  exclude:
    entities:
      - sensor.average_load_1m
      - sensor.average_load_5m
      - sensor.average_load_15m
      - sensor.since_last_boot
      - sensor.ram_used
      - sensor.disk_used_
      - sensor.disk_used_mnt
      - sensor.speedtest_download
      - sensor.last_backup
      - sensor.desk_lights_energy
      - sun.sun
      - camera.drive
      - camera.hall
      - camera.landing
      - camera.garden
      - camera.thomas
      - zwave.office
      - zwave.desk_lights
      - group.all_switches
      - sensor.pihole_ads_percentage_today
      - group.all_motion_sensors
      - group.pihole_stats
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_ads_blocked_today
      - sensor.lights_on_count
      - automation.turn_on_office_lights_on_motion

updater:
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
camera: !include cameras.yaml
weblink: !include weblinks.yaml
discovery:
history:
logbook:
  exclude:
    entities:
      - sensor.average_load_15m
      - sensor.average_load_1m
      - sensor.since_last_boot
      - sensor.average_load_5m
      - group.all_motion_sensors
      - group.thomas
logger:
  default: warn
  logs:
    #suppress the foscam errors
    urllib3.connectionpool: critical
map:
sun:
ios:
device_tracker:

zwave:
  usb_path: /dev/ttyACM0
  
tradfri:
  host: 192.168.1.97
  allow_tradfri_groups: false
zone:
  - name: SEL
    latitude: 53.201563
    longitude: -0.590652
    icon: mdi:laptop-mac
  - name: Saxilby School
    latitude: 53.268870
    longitude: -0.657313
    icon: mdi:school

shell_command: !include shell_commands.yaml

switch:
  - platform: tplink
    host: 192.168.1.117

binary_sensor:
  - platform: mqtt
    state_topic: 'home/nodemcu/1/motion'
    device_class: 'motion'
    name: 'nodemcu1'
    value_template: ' {{ value_json.motion }}'
  - platform: command_line
    name: hall_motion
    command:  !secret get_hall_motion_status
    value_template: >-
      {%- if value == "2" -%}
        motion
      {%- else -%}
        none
      {%- endif -%}
    payload_on: motion
    payload_off: none
    device_class: motion
    scan_interval: 5
  - platform: command_line
    name: landing_motion
    command:  !secret get_landing_motion_status
    value_template: >-
      {%- if value == "2" -%}
        motion
      {%- else -%}
        none
      {%- endif -%}
    payload_on: motion
    payload_off: none
    device_class: motion
    scan_interval: 5

input_boolean:
  enable_security:
    initial: on

panel_custom:
  - name: floorplan
    sidebar_title: Floor Plan (Desktop)
    sidebar_icon: mdi:floor-plan
    url_path: desktop
    config: !include floorplan2.yaml

  - name: floorplan
    sidebar_title: Floor Plan (Mobile)
    sidebar_icon: mdi:floor-plan
    url_path: mobile
    config: !include floorplan.yaml